### ISSUE TITLE
提issues之前，先看这里

### ISSUE THREAD

**Issue by xueandyue** [xueandyue/ChatGPT-AccessToken-Web#16]
1.不支持k8s部署，只支持docker部署
2.不支持vercel部署
3.确保是按以下的docker镜像版本和docker命令部署，其他版本的不要提，维护的docker镜像版本 xueandyue/next-web-pandora:latest  和  xueandyue/next-web-pandora:accessToken ，xueandyue/next-web-pandora:accessToken2

4.报错信息，请附上docker logs
5.先看下之前别人提的issues,避免重复提issue
6.不懂用docker部署的，去网上查看下教程
7.如果是提示 Conversation not found ,表示当前聊天窗口过期，要新开一个聊天窗口对话
8.先认真看一遍README.md文件

**Comment by vssnipper** [comment]
感谢大佬，这个能做账号轮询机制吗？多人访问似乎有点不够。

**Comment by xueandyue** [comment]
> 感谢大佬，这个能做账号轮询机制吗？多人访问似乎有点不够。

暂无计划

**Comment by ItsZhengyd** [comment]
前几天pandora作者pengzhile搞了个破解copilot的项目开源到GitHub，老虎嘴里拔牙，然后被封，账号和项目全都404了 ,,ԾㅂԾ,,

**Comment by xueandyue** [comment]
ԾㅂԾ,pengzhile大佬大强了，有clone一份破解copilot的项目吗？

**Comment by ItsZhengyd** [comment]
> ԾㅂԾ,pengzhile大佬大强了，有clone一份破解copilot的项目吗？

我抖音刷到的时候就去看了，已经没了

**Comment by hansonhantong** [comment]
现在好像都不行了吧 部署了之后一直报错
![image](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/22970644/f4a6772b-05bc-47ff-affd-de6a1e536498)

**Comment by xueandyue** [comment]
> 现在好像都不行了吧 部署了之后一直报错 ![image](https://user-images.githubusercontent.com/22970644/274526168-f4a6772b-05bc-47ff-affd-de6a1e536498.png)

在应用上用新开的聊天窗口，进行对话试试。

**Comment by jayceftg** [comment]
不存在
