### ISSUE TITLE
实现vercel部署前端，后端用python获取fakeKey

### ISSUE THREAD

**Issue by Yanyutin753** [xueandyue/ChatGPT-AccessToken-Web#24]
我今天把前端代码修改了，通过一键刷新，请求后端接口，刷新gpt，获取到fakeKey，程序能正常使用，但是感觉这样还是很麻烦，能不能想个办法不用后端，直接vercel部署，用vercel直接拿到用户名，密码变量，直接获取到fakeKey，因为很大一部分人都是vercel部署的

**Comment by xueandyue** [comment]
是的，行得通。例如直接获取到fakeKey，然后访问FakeGPT服务，这样就可以不用部署后端了。

**Comment by xueandyue** [comment]
如果FakeGPT稳定，是可以这样考虑

**Comment by Yanyutin753** [comment]
对啊，就看稳不稳定，感觉可以往这方向看看，搞个通用的api，来转接获取apikey，那这样都不用搭后端了

**Comment by Yanyutin753** [comment]
![8221365fbbd6ff5cd7d1f7166815d67](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/132346501/a086678d-dc7c-4e7c-8b48-d588681d232e)我是这样刷新就能用了，但是现在用不了code

**Comment by Yanyutin753** [comment]
因为现在替换的是用户的apikey，没有换环境变量的key，请教环境变量的key,咋换的哇，不是刷新之后或者清除缓存之后就会恢复原样了嘛

**Comment by xueandyue** [comment]
直接用前端通过用户名，密码访问https://[chat1.zhile.io/auth/login?v=5](https://chat1.zhile.io/auth/login?v=5)，模拟登录获取accesstoken,然后用这个accesstoken调它的接口。

**Comment by xueandyue** [comment]
> 因为现在替换的是用户的apikey，没有换环境变量的key，请教环境变量的key,咋换的哇，不是刷新之后或者清除缓存之后就会恢复原样了嘛

在我这个项目apikey是没用的，环境变量是设置访问密码。vercel部署的时候可以设置环境变量吧

**Comment by Yanyutin753** [comment]
我拿不到，拿到一堆html

**Comment by Yanyutin753** [comment]
该怎么获取呢

**Comment by xueandyue** [comment]
我后面再看看，可能pengzhile大佬加了额外的防护也不一定

**Comment by Yanyutin753** [comment]
访问不了奇怪，要真人识别

**Comment by Yanyutin753** [comment]
![image](https://github.com/xueandyue/ChatGPT-3.5-AccessToken-Web/assets/132346501/05453026-493a-4898-a804-d59313e8f337)

**Comment by kognmengyu666** [comment]
可以分享一下您这个修改了以后得代码嘛
