### ISSUE TITLE
3 question need help, this project is really great.

### ISSUE THREAD

**Issue by SmilingEOS** [xueandyue/ChatGPT-AccessToken-Web#29]
I’ve deployed it directly to the IP address on VPS.
I have a few questions to ask: 

1. Is ChatGPT Plus available? 
2. Are the GPTs features announced at the developer conference available? 
3. Is it possible to provide a clean and simple ChatGPT native interface option?

Thanks.

**Comment by xueandyue** [comment]
1. This project has a gpt4 branch, but it will no longer be updated. I recommend another project for you: https://chat1.zhile.io/auth/login?v=5"
2. This project is no longer being updated. I recommend another project for you: https://chat1.zhile.io/auth/login?v=5
3. No, there is no such plan. I recommend another project for you: https://chat1.zhile.io/auth/login?v=5
