### ISSUE TITLE
 docker: Error response from daemon: create ./data: "./data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

### ISSUE THREAD

**Issue by King6880** [xueandyue/ChatGPT-AccessToken-Web#34]
docker: Error response from daemon: create ./data: "./data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

**Comment by xueandyue** [comment]
docker run -d --restart always --name PandoraNext --net=my-net -v ./data:/data -v ./sessions:/root/.cache/PandoraNext pengzhile/pandora-next  你的执行这命令的目录中有data目录吗？ 如果目录没错，还是不行的话，你把相对的路径改为绝对路径试试

**Comment by xueandyue** [comment]
你是用windows上用docker？ 那只能改用绝对路径了

**Comment by King6880** [comment]
如果前缀强度不合格，启动时会提示"proxy_api_prefix" < 8 chars or too weak, proxy mode off!，并且不会启用代理模式。

**Comment by King6880** [comment]
能加个联系方式请教下吗，确实没找到配置文件的默认值在哪儿 感谢

**Comment by xueandyue** [comment]
https://github.com/xueandyue/ChatGPT-AccessToken-Web/blob/main/pandoranext-deploy.zip

**Comment by xueandyue** [comment]
![image](https://github.com/xueandyue/ChatGPT-AccessToken-Web/assets/16577210/3e2327c3-798e-4434-9fe5-30b38b941176)

**Comment by King6880** [comment]
> ![image](https://private-user-images.githubusercontent.com/16577210/295519393-3e2327c3-798e-4434-9fe5-30b38b941176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzk3ODYsIm5iZiI6MTcwNDg3OTQ4NiwicGF0aCI6Ii8xNjU3NzIxMC8yOTU1MTkzOTMtM2UyMzI3YzMtNzk4ZS00NDM0LTlmZTUtMzBiMzhiOTQxMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA5MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMTFmZGQ2YTc4YzY4OGIyZGU2ZTFjNWIxZGVkZWQ4N2EyNjgyM2VmOTYwYmNmNTU2N2IyMTc3Yzk5NGVmNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AVhhDLAgXOj9R3zE6YqHxxIdqpiOvod5kuQShDQ8V1w)

谢谢大佬
